spring.application.name=control-plane
server.port=9090

# Application Configuration

app.chunk-size-bytes=5242880
app.upload.session.ttl-seconds=86400


# Database configuration

spring.datasource.url=jdbc:postgresql://localhost:5433/cloudfold
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
